engines:
  cppcheck:
    enabled: true
    config:
      check: all
      project: compile_commands.json
      language: c++
      stds:
        - c++11
      platform: unix64   
      defines:
      - "__cplusplus"
      includes:
      - http/
      - tinyxml2/
      inconclusive: false
  fixme:
    enabled: true
exclude_patterns:
- "tinyxml2/*"
