language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
matrix:
  allow_failures:
    - os: osx
script:
  make all

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openssl ; fi
