language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
matrix:
  allow_failures:
    - os: osx
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      CFLAGS="-I/usr/local/opt/openssl/include $CFLAGS"
      LDFLAGS="-L/usr/local/opt/openssl/lib $LDFLAGS"
    fi
script:
  make all
